### ISSUE TITLE
esp_codec_dev regression (AUD-4685)

### ISSUE THREAD

**Issue by tore-espressif** [espressif/esp-adf#1024]
Hello esp-adf team,
I really like your esp_codec_dev component! I think I found a regression in latest 1.0.2 release:
`playback` is evaluated to `true` on this line https://github.com/espressif/esp-adf/blob/master/components/esp_codec_dev/platform/audio_codec_data_i2s.c#L350 for `ESP_CODEC_DEV_TYPE_IN_OUT`, so then RX channel is not enabled when `_i2s_drv_enable()` is called on line 365

Could you please take a look?

**Comment by TempoTian** [comment]
Thanks  for your information.
Yes, it is a regression, I will fix it soon.
When update to IDF 5.x, if use one handle to do playback and record at same time, it will have issue.
But it is recommend to use 2 handle for playback and record seperately, so that each handle can use different settting such as bits per sample to use the filter capability of new i2s driver.
IDF4.x is not affected for that channel enable function is not provided yet.
