### ISSUE TITLE
Eclipse indexer don't work (AUD-565)

### ISSUE THREAD

**Issue by dumarjo** [espressif/esp-adf#201]
Hi,

I try to get the indexer working with eclipse. I followed the tutorial for the IDF thing (replacing the IDF_PATH by ADF_PATH), but I can't get it working. 

Is it possible to have it working ?

Jonathan

**Comment by Piocky** [comment]
Hi,

I think i've got the same issue: I imported the HTTP_MP3 example from the ADF folder, followed the procedure as described from this [link](https://docs.espressif.com/projects/esp-idf/en/stable/get-started/eclipse-setup.html), added the ADF_PATH, my project build without error in the console, but in the problems tab, i've got a lot of issues because Eclipse can't find the headers files from ADF.

Did you find anything since june by any chance? Or anyone else?

Yoann

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
