### ISSUE TITLE
How to use the recorder engine？ And how  to use rec_engine_data_read or rec_engine_enc_data_read to get the voice data save into SD card or  HTTP server? (AUD-2603)

### ISSUE THREAD

**Issue by hulife** [espressif/esp-adf#536]
如题，如何使用这些函数实现数据的保存（当发出语音后，开启vad监测，语音停止，vad关闭，数据保存下来）

**Comment by michalber** [comment]
Hey
VAD events are set in the recorder engine. You need to provide callback functions, such as I2S open/close/read callback functions, and recorder engine events callback function. Also you will need a task to gather recorded data when rec_eng will wake up (to store "command" audio). Dueros example is using recorder engine so that is the best way to learn how it is working.

DuerOS rec_eng_callback:
https://github.com/espressif/esp-adf/blob/master/examples/dueros/main/dueros_app.c#L82

DuerOS service task to gather "command" audio:
https://github.com/espressif/esp-adf/blob/master/components/dueros_service/dueros_service.c#L220
