### ISSUE TITLE
How to use audio_element_seek() with mp3 decoder ? (AUD-3440)

### ISSUE THREAD

**Issue by vovan888** [espressif/esp-adf#721]
I need to seek to a position in seconds while playing an mp3 file using audio pipeline. How to do it ?

**Comment by NikkSaan** [comment]
I'd like to know as well! Did you find a solution? I want to make an audio player using pipeline instead of esp_audio which is proprietary and does't support EQ. Also I'm wandering about getting total time of a file and elapsed time... If they have provided us with the source of esp_audio finding this out would be easy!

**Comment by jason-mao** [comment]
Seek is complicated operation with different music source, we do not support independent element seek currently, recommend use `esp_audio` APIs. 

And, I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
