### ISSUE TITLE
mixer Example How to mix more than four audios (AUD-3792)

### ISSUE THREAD

**Issue by maozhifeng** [espressif/esp-adf#810]
My current use Example, mix two audios and he works great. But now I want to mix more than 4 audio, do not know how to operate, please ask it.

**Comment by HengYongChao** [comment]
Hi @maozhifeng 

As I mentioned in the [downmix_pipeline#troubleshooting](https://github.com/espressif/esp-adf/tree/master/examples/advanced_examples/downmix_pipeline#troubleshooting), the limited reason in downmix example  is the cpu loading caused by simultaneous decoding. If your audio source is wav/pcm data, I think mix 4 channels is possible.
